import { useState } from 'react';
import Card from '../../components/common/Card';
import Badge from '../../components/common/Badge';
import DateRangePicker from '../../components/common/DateRangePicker';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, AreaChart, Area } from 'recharts';

const Analytics = () => {
  const [activeTab, setActiveTab] = useState('movement');
  const tabs = [{ key: 'movement', label: 'Movement' }, { key: 'overspeed', label: 'Overspeed' }, { key: 'parked', label: 'Parked' }, { key: 'idle', label: 'Idle' }, { key: 'ignition', label: 'Ignition' }];
  const pieData = [{ name: 'Moving', value: 65, color: '#34d8b5' }, { name: 'Idle', value: 20, color: '#fbbf24' }, { name: 'Parked', value: 10, color: '#f87171' }, { name: 'Offline', value: 5, color: '#64748b' }];
  const movementData = [{ hour: '00', count: 2 }, { hour: '04', count: 1 }, { hour: '08', count: 12 }, { hour: '12', count: 18 }, { hour: '16', count: 15 }, { hour: '20', count: 8 }];
  const overspeedData = [{ vehicle: 'VH-001', count: 3, maxSpeed: 95 }, { vehicle: 'VH-002', count: 1, maxSpeed: 88 }, { vehicle: 'VH-003', count: 5, maxSpeed: 102 }];
  const idleData = [{ name: 'VH-001', idle: 45, moving: 155 }, { name: 'VH-002', idle: 30, moving: 170 }, { name: 'VH-003', idle: 60, moving: 140 }];

  return (
    <div className="space-y-6 animate-fadeIn">
      <Card><div className="flex items-center justify-between flex-wrap gap-4"><div className="flex gap-2">{tabs.map((tab) => (<button key={tab.key} onClick={() => setActiveTab(tab.key)} className={`px-4 py-2 rounded-xl text-xs font-semibold uppercase tracking-wider transition-all ${activeTab === tab.key ? 'bg-accent text-white shadow-[0_4px_16px_rgba(2,120,201,0.25)]' : 'bg-lb-50 text-muted hover:bg-[rgba(56,175,249,0.06)]'}`}>{tab.label}</button>))}</div><DateRangePicker onChange={() => {}} /></div></Card>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card><h3 className="font-semibold text-sm text-text-primary font-display mb-4">Status Distribution</h3><ResponsiveContainer width="100%" height={200}><PieChart><Pie data={pieData} cx="50%" cy="50%" innerRadius={50} outerRadius={80} dataKey="value" paddingAngle={3}>{pieData.map((entry, i) => <Cell key={i} fill={entry.color} />)}</Pie><Tooltip contentStyle={{ backgroundColor: 'rgba(7,81,134,0.88)', border: 'none', borderRadius: '8px', color: 'white', fontSize: '12px' }} /></PieChart></ResponsiveContainer><div className="grid grid-cols-2 gap-2 mt-2">{pieData.map((item) => <div key={item.name} className="flex items-center gap-2 text-xs"><span className="w-2 h-2 rounded-full" style={{ background: item.color }} /><span className="text-muted">{item.name}</span><span className="ml-auto font-semibold text-text-primary">{item.value}%</span></div>)}</div></Card>
        <Card className="lg:col-span-2"><h3 className="font-semibold text-sm text-text-primary font-display mb-4">Movement by Hour</h3><ResponsiveContainer width="100%" height={220}><AreaChart data={movementData}><defs><linearGradient id="mvGrad" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#38aff9" stopOpacity={0.3} /><stop offset="95%" stopColor="#38aff9" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="rgba(56,175,249,0.1)" /><XAxis dataKey="hour" tick={{ fontSize: 10, fill: '#64748b' }} /><YAxis tick={{ fontSize: 10, fill: '#64748b' }} /><Tooltip contentStyle={{ backgroundColor: 'rgba(7,81,134,0.88)', border: 'none', borderRadius: '8px', color: 'white', fontSize: '12px' }} /><Area type="monotone" dataKey="count" stroke="#38aff9" strokeWidth={2} fill="url(#mvGrad)" /></AreaChart></ResponsiveContainer></Card>
      </div>
      <Card><h3 className="font-semibold text-sm text-text-primary font-display mb-4">Overspeed Incidents</h3><div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-[rgba(56,175,249,0.18)]">{['Vehicle', 'Incidents', 'Max Speed', 'Limit', 'Status'].map((h) => <th key={h} className="text-left py-3 px-4 text-[10px] font-semibold uppercase tracking-widest text-muted">{h}</th>)}</tr></thead><tbody>{overspeedData.map((row, i) => (<tr key={i} className="border-b border-[rgba(56,175,249,0.1)] hover:bg-[rgba(218,241,255,0.6)] transition-colors"><td className="py-3 px-4 text-sm font-medium text-text-primary">{row.vehicle}</td><td className="py-3 px-4 text-sm text-text-primary">{row.count}</td><td className="py-3 px-4 text-sm text-text-primary font-semibold">{row.maxSpeed} km/h</td><td className="py-3 px-4 text-sm text-muted">80 km/h</td><td className="py-3 px-4"><Badge variant="warning">+{(row.maxSpeed - 80).toFixed(0)} km/h</Badge></td></tr>))}</tbody></table></div></Card>
      <Card><h3 className="font-semibold text-sm text-text-primary font-display mb-4">Idle vs Moving Time (hours)</h3><ResponsiveContainer width="100%" height={250}><BarChart data={idleData} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke="rgba(56,175,249,0.1)" /><XAxis type="number" tick={{ fontSize: 10, fill: '#64748b' }} /><YAxis dataKey="name" type="category" tick={{ fontSize: 10, fill: '#64748b' }} /><Tooltip contentStyle={{ backgroundColor: 'rgba(7,81,134,0.88)', border: 'none', borderRadius: '8px', color: 'white', fontSize: '12px' }} /><Bar dataKey="idle" fill="#fbbf24" stackId="a" radius={[0, 0, 0, 0]} name="Idle" /><Bar dataKey="moving" fill="#34d8b5" stackId="a" radius={[0, 4, 4, 0]} name="Moving" /></BarChart></ResponsiveContainer></Card>
    </div>
  );
};
export default Analytics;
